Atualização

diff --git a/.github/workflows/010_cleanup_artifacts.yml b/.github/workflows/010_cleanup_artifacts.yml
--- a/.github/workflows/010_cleanup_artifacts.yml
+++ b/.github/workflows/010_cleanup_artifacts.yml
@@ -14,39 +14,29 @@ concurrency:
   cancel-in-progress: false
   
 jobs:
-  precheck:
+  # ==========================================================
+  # 🧩 JOB 1: Verifica se a infraestrutura AWS está OK
+  # ==========================================================
+  infra-check:
+    uses: ./.github/workflows/002_check_infra_aws.yml
+    secrets: inherit
+
+  print-infra-output:
+    name: Resultado da Verificação de Infraestrutura
+    needs: infra-check
     runs-on: ubuntu-latest
-    outputs:
-      deploy_allowed: ${{ steps.deploy_check.outputs.deploy_allowed }}
-      
     steps:
-      - name: Checkout
-        uses: actions/checkout@v4
-
-      - name: Install jq
-        run: sudo apt-get update && sudo apt-get install -y jq
-
-      - name: Download apply_status artifact (from Setup Infra)
-        uses: dawidd6/action-download-artifact@v3
-        with:
-          workflow: 001_setup_infra_aws.yml
-          name: terraform-apply-status
-          path: .
-
-      - name: Check apply_status
-        id: deploy_check
+      - name: 🖨 Print Infra Output
         run: |
-          if [ ! -f ./apply_status.txt ]; then
-            echo "deploy_allowed=false" >> $GITHUB_OUTPUT
-            exit 0
+          echo "📢 Infra AWS ainda existe?: ${{ needs.infra-check.outputs.infra_is_ready }}"
+          if [ "${{ needs.infra-check.outputs.infra_is_ready }}" == "true" ]; then
+            echo "❌ Infra ainda está criada, abortando!"
+            exit 1
           fi
-          APPLY_STATUS=$(jq -r '.apply' ./apply_status.txt)
-          if [[ "$APPLY_STATUS" == "success" ]]; then
-            echo "deploy_allowed=true" >> $GITHUB_OUTPUT
-          else
-            echo "deploy_allowed=false" >> $GITHUB_OUTPUT
-          fi
-     
+
+  # ==========================================================
+  # 🚀 JOB 2:Remove Infra AWS
+  # ==========================================================
   cleanup:
     name: 🧹 Remover Artifacts Antigos
     runs-on: ubuntu-latest
