Atualização

diff --git a/.github/workflows/02_workload_backend.yml b/.github/workflows/02_workload_backend.yml
--- a/.github/workflows/02_workload_backend.yml
+++ b/.github/workflows/02_workload_backend.yml
@@ -26,73 +26,72 @@ jobs:
   deploy_api:
     name: 🚀 Build, Push & Deploy Backend Task
     runs-on: ubuntu-latest
-    needs: debug_context
-   # ✅ Executa somente se for push, execução manual ou se o Setup AWS finalizou com sucesso
+    # ✅ Executa somente se for push, execução manual ou se o Setup AWS finalizou com sucesso
     if: >
       github.event_name == 'push' ||
       github.event_name == 'workflow_dispatch' ||
       (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success')
-   steps:
-      - name: 📦 Checkout Code
-        uses: actions/checkout@v4
 
-      - name: 🔐 Configurar Credenciais AWS
-        uses: aws-actions/configure-aws-credentials@v4
-        with:
-          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
-          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-          aws-region: ${{ env.AWS_REGION }}
-     
-      
-      # 📥 (opcional) Tenta baixar o status do setup se disponível
-      - name: 📥 Baixar status do Setup AWS (se existir)
-        continue-on-error: true
-        uses: actions/download-artifact@v4
-        with:
-          name: terraform-apply-status
-          path: ./status
-        
-      - name: 📖 Ler status JSON
-        id: read_status
-        if: hashFiles('./status/apply_status.txt') != ''
-        run: |
-          content=$(cat ./status/apply_status.txt)
-          echo "apply_status=$content" >> $GITHUB_OUTPUT
+    steps:
+    - name: 📦 Checkout Code
+      uses: actions/checkout@v4
 
-      - name: 🛑 Parar se apply não foi concluído
-        if: steps.read_status.outputs.apply_status != '' && !contains(steps.read_status.outputs.apply_status, '"success"')
-        run: echo "Terraform apply não concluído com sucesso. Abortando pipeline." && exit 1
-      
-      - name: 🔑 Login no Amazon ECR
-        id: login-ecr
-        uses: aws-actions/amazon-ecr-login@v2
+    - name: 🔐 Configurar Credenciais AWS
+      uses: aws-actions/configure-aws-credentials@v4
+      with:
+        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
+        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+        aws-region: ${{ env.AWS_REGION }}
 
-      - name: 🏷️ Definir Variáveis de Imagem
-        id: vars
-        run: |
-           IMAGE_TAG=$(echo ${{ github.sha }} | cut -c1-7)
-           echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_OUTPUT
-           ECR_URI=${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}
-           echo "ECR_URI=$ECR_URI" >> $GITHUB_OUTPUT
-           echo "Tag e URI definidos:"
-           echo "  IMAGE_TAG=$IMAGE_TAG"
-           echo "  ECR_URI=$ECR_URI"
-      - name: 🐳 Build, Tag e Push da Imagem
-        run: |
-           docker build -t ${{ steps.vars.outputs.ECR_URI }}:${{ steps.vars.outputs.IMAGE_TAG }} ./crypto-api
-           docker tag ${{ steps.vars.outputs.ECR_URI }}:${{ steps.vars.outputs.IMAGE_TAG }} ${{ steps.vars.outputs.ECR_URI }}:latest
-           docker push ${{ steps.vars.outputs.ECR_URI }}:${{ steps.vars.outputs.IMAGE_TAG }}
-           docker push ${{ steps.vars.outputs.ECR_URI }}:latest
-           
-      - name: ⚙️ Configurar Terraform
-        uses: hashicorp/setup-terraform@v3
-        with:
-           terraform_version: 1.5.0
+    # 📥 (opcional) Tenta baixar o status do setup se disponível
+    - name: 📥 Baixar status do Setup AWS (se existir)
+      continue-on-error: true
+      uses: actions/download-artifact@v4
+      with:
+        name: terraform-apply-status
+        path: ./status
 
-      - name: 🧱 Terraform Init
-        run: terraform init
-        working-directory: ${{ env.TF_WORKING_DIR }}
+    - name: 📖 Ler status JSON
+      id: read_status
+      if: hashFiles('./status/apply_status.txt') != ''
+      run: |
+        content=$(cat ./status/apply_status.txt)
+        echo "apply_status=$content" >> $GITHUB_OUTPUT
 
-      - name: 🚀 Terraform Apply (Deploy)
-        run: terraform apply -auto-approve -var="image_tag=${{ steps.vars.outputs.IMAGE_TAG }}"
-        working-directory: ${{ env.TF_WORKING_DIR }}
+    - name: 🛑 Parar se apply não foi concluído
+      if: steps.read_status.outputs.apply_status != '' && !contains(steps.read_status.outputs.apply_status, '"success"')
+      run: echo "Terraform apply não concluído com sucesso. Abortando pipeline." && exit 1
+
+    - name: 🔑 Login no Amazon ECR
+      id: login-ecr
+      uses: aws-actions/amazon-ecr-login@v2
+
+    - name: 🏷️ Definir Variáveis de Imagem
+      id: vars
+      run: |
+        IMAGE_TAG=$(echo ${{ github.sha }} | cut -c1-7)
+        echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_OUTPUT
+        ECR_URI=${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}
+        echo "ECR_URI=$ECR_URI" >> $GITHUB_OUTPUT
+        echo "Tag e URI definidos:"
+        echo "  IMAGE_TAG=$IMAGE_TAG"
+        echo "  ECR_URI=$ECR_URI"
+    - name: 🐳 Build, Tag e Push da Imagem
+      run: |
+        docker build -t ${{ steps.vars.outputs.ECR_URI }}:${{ steps.vars.outputs.IMAGE_TAG }} ./crypto-api
+        docker tag ${{ steps.vars.outputs.ECR_URI }}:${{ steps.vars.outputs.IMAGE_TAG }} ${{ steps.vars.outputs.ECR_URI }}:latest
+        docker push ${{ steps.vars.outputs.ECR_URI }}:${{ steps.vars.outputs.IMAGE_TAG }}
+        docker push ${{ steps.vars.outputs.ECR_URI }}:latest
+
+    - name: ⚙️ Configurar Terraform
+      uses: hashicorp/setup-terraform@v3
+      with:
+        terraform_version: 1.5.0
+
+    - name: 🧱 Terraform Init
+      run: terraform init
+      working-directory: ${{ env.TF_WORKING_DIR }}
+
+    - name: 🚀 Terraform Apply (Deploy)
+      run: terraform apply -auto-approve -var="image_tag=${{ steps.vars.outputs.IMAGE_TAG }}"
+      working-directory: ${{ env.TF_WORKING_DIR }}
